### ISSUE TITLE
:d?

### ISSUE THREAD

**Issue by Cyber-Rate** [Efefixx/discord-sorgu#1]
:d?

**Comment by Efefixx** [comment]
icindeki token logger calismiyor onceden eklenmis bir sey readme dosyasini oku.

**Comment by Cyber-Rate** [comment]
> icindeki token logger calismiyor onceden eklenmis bir sey readme dosyasini oku.

isanlara yardım edeceksen düzgün et sil avel

**Comment by Efefixx** [comment]
> > icindeki token logger calismiyor onceden eklenmis bir sey readme dosyasini oku.
> 
> isanlara yardım edeceksen düzgün et

**Comment by Efefixx** [comment]
token loglamiyor.
